version: "3.9"
services:
    web:
        container_name: wolfpack
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
        environment:
            ASPNETCORE_URLS: "http://*:80"
            ConnectionStrings__Database: "Server=db;Database=wolfpack;User=sa;Password=JoinTheWolfPackIn2022!"

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "JoinTheWolfPackIn2022!"
            ACCEPT_EULA: "Y"
